
    create table Categoria (
        id bigint generated by default as identity (start with 1),
        nombre varchar(255),
        primary key (id)
    )

    create table Categoria_Funcionalidad (
        Categoria_id bigint not null,
        funcionalidades_id bigint not null
    )

    create table Direccion (
        id bigint generated by default as identity (start with 1),
        altura integer not null,
        calle varchar(255),
        piso integer not null,
        primary key (id)
    )

    create table DireccionPostal (
        id bigint generated by default as identity (start with 1),
        ciudad varchar(255),
        codigoPostal integer not null,
        pais varchar(255),
        provincia varchar(255),
        direccion_id bigint,
        primary key (id)
    )

    create table DocumentoComercial (
        id bigint generated by default as identity (start with 1),
        numeroDeOperacion integer not null,
        tipoDocumento integer,
        primary key (id)
    )

    create table Empresa (
        CUIT double not null,
        tipo integer,
        id bigint not null,
        primary key (id)
    )

    create table Entidad (
        id bigint generated by default as identity (start with 1),
        categoria_id bigint,
        primary key (id)
    )

    create table EntidadBase (
        descripcion varchar(255),
        nombreFicticio varchar(255),
        id bigint not null,
        entidadJuridica_id bigint,
        primary key (id)
    )

    create table EntidadJuridica (
        razonSocial varchar(255),
        id bigint not null,
        primary key (id)
    )

    create table Etiqueta (
        identificador varchar(255) not null,
        primary key (identificador)
    )

    create table Funcionalidad (
        DTYPE varchar(31) not null,
        id bigint generated by default as identity (start with 1),
        cantidadDeOperaciones integer,
        entJuridica_id bigint,
        primary key (id)
    )

    create table Item (
        id bigint generated by default as identity (start with 1),
        descripcion varchar(255),
        detalle varchar(255),
        valor numeric(19,2),
        egresoAsociado_id bigint,
        moneda_id bigint,
        Presupuesto_id bigint,
        primary key (id)
    )

    create table MedioDePago (
        DTYPE varchar(31) not null,
        id bigint generated by default as identity (start with 1),
        tipo integer,
        primary key (id)
    )

    create table Mensaje (
        id bigint generated by default as identity (start with 1),
        egresoValido boolean,
        egresoRelacionado_id bigint,
        Usuario_id bigint,
        primary key (id)
    )

    create table Moneda (
        id bigint generated by default as identity (start with 1),
        descripcion varchar(255),
        lugaresDecimal integer not null,
        siglas varchar(255),
        simbolo varchar(255),
        primary key (id)
    )

    create table OSC (
        cantEgresosAceptados integer not null,
        id bigint not null,
        primary key (id)
    )

    create table OperacionDeEgreso (
        id bigint generated by default as identity (start with 1),
        fecha varbinary(255),
        resultadoDeValidacion integer,
        documentoComercial_id bigint,
        medioDePago_id bigint,
        presupuestoElegido_id bigint,
        proveedor_id bigint,
        entidad_id bigint,
        primary key (id)
    )

    create table OperacionDeEgreso_Etiqueta (
        OperacionDeEgreso_id bigint not null,
        etiquetas_identificador varchar(255) not null
    )

    create table OperacionDeEgreso_Usuario (
        OperacionDeEgreso_id bigint not null,
        usuariosRevisores_id bigint not null
    )

    create table OperacionDeEgreso_ValidacionPresupuestos (
        OperacionDeEgreso_id bigint not null,
        validacionesPresupuesto_id bigint not null
    )

    create table Presupuesto (
        id bigint generated by default as identity (start with 1),
        OperacionDeEgreso_id bigint,
        primary key (id)
    )

    create table Proveedor (
        id bigint generated by default as identity (start with 1),
        apellido varchar(255),
        nombre varchar(255),
        razonSocial varchar(255),
        direccionPostal_id bigint,
        primary key (id)
    )

    create table Reporte (
        id bigint generated by default as identity (start with 1),
        fecha varbinary(255),
        etiqueta_identificador varchar(255),
        primary key (id)
    )

    create table Reporte_OperacionDeEgreso (
        Reporte_id bigint not null,
        operaciones_id bigint not null
    )

    create table TipoUsuario (
        DTYPE varchar(31) not null,
        id bigint generated by default as identity (start with 1),
        primary key (id)
    )

    create table Usuario (
        id bigint generated by default as identity (start with 1),
        password varbinary(255),
        user varchar(255),
        tipo_id bigint,
        primary key (id)
    )

    create table ValidacionPresupuestos (
        DTYPE varchar(31) not null,
        id bigint generated by default as identity (start with 1),
        primary key (id)
    )

    alter table Reporte_OperacionDeEgreso 
        add constraint UK_e9qochl24fekyaq6i3eir94uh  unique (operaciones_id)

    alter table Categoria_Funcionalidad 
        add constraint FK_n85kd2os0xt4ls10nm1nigm8g 
        foreign key (funcionalidades_id) 
        references Funcionalidad

    alter table Categoria_Funcionalidad 
        add constraint FK_gj1fp9o8b2te0detnmfmyjr26 
        foreign key (Categoria_id) 
        references Categoria

    alter table DireccionPostal 
        add constraint FK_qwhui7vtxhnbk0lcjy4d7j7lx 
        foreign key (direccion_id) 
        references Direccion

    alter table Empresa 
        add constraint FK_eg477mv2yqmlrfnj2svapcprm 
        foreign key (id) 
        references EntidadJuridica

    alter table Entidad 
        add constraint FK_80o0otto4a1hahbogdlsx759d 
        foreign key (categoria_id) 
        references Categoria

    alter table EntidadBase 
        add constraint FK_jipg66mf5t7h6ri6acnhne03c 
        foreign key (entidadJuridica_id) 
        references EntidadJuridica

    alter table EntidadBase 
        add constraint FK_8r7yhl4vpqnlkm6ddaa4rpd6c 
        foreign key (id) 
        references Entidad

    alter table EntidadJuridica 
        add constraint FK_pcrp9vdj0cllsldpnw126n1be 
        foreign key (id) 
        references Entidad

    alter table Funcionalidad 
        add constraint FK_2rmvmu54cxxkuluiawddw05qm 
        foreign key (entJuridica_id) 
        references EntidadJuridica

    alter table Item 
        add constraint FK_try0nrqx7fpqos0kyop6ferx0 
        foreign key (egresoAsociado_id) 
        references OperacionDeEgreso

    alter table Item 
        add constraint FK_li0t8pn2esqvdhutaj23yyhcd 
        foreign key (moneda_id) 
        references Moneda

    alter table Item 
        add constraint FK_8h7xi9i1tp1yblkkje6793715 
        foreign key (Presupuesto_id) 
        references Presupuesto

    alter table Mensaje 
        add constraint FK_3wik8x0hdplci4l4k3bwk1fac 
        foreign key (egresoRelacionado_id) 
        references OperacionDeEgreso

    alter table Mensaje 
        add constraint FK_s6si3uh6v9hx9304ql4khwyc5 
        foreign key (Usuario_id) 
        references Usuario

    alter table OSC 
        add constraint FK_gmhfsybiilhfb8nrjhgl38bgg 
        foreign key (id) 
        references EntidadJuridica

    alter table OperacionDeEgreso 
        add constraint FK_mb29y1tv83fj12c08j9xx5kff 
        foreign key (documentoComercial_id) 
        references DocumentoComercial

    alter table OperacionDeEgreso 
        add constraint FK_3swq7rbf4wsyo554s68um5yxm 
        foreign key (medioDePago_id) 
        references MedioDePago

    alter table OperacionDeEgreso 
        add constraint FK_qytv3kblmgd400ej5chbh3fx0 
        foreign key (presupuestoElegido_id) 
        references Presupuesto

    alter table OperacionDeEgreso 
        add constraint FK_14k7g14y9ln23d1vdaffiq2wq 
        foreign key (proveedor_id) 
        references Proveedor

    alter table OperacionDeEgreso 
        add constraint FK_cub84362wthi77sojrjeo98o7 
        foreign key (entidad_id) 
        references Entidad

    alter table OperacionDeEgreso_Etiqueta 
        add constraint FK_1bclasuts1cu6j2dflfekg70v 
        foreign key (etiquetas_identificador) 
        references Etiqueta

    alter table OperacionDeEgreso_Etiqueta 
        add constraint FK_jg4dn3s67bmbek39x63d2880x 
        foreign key (OperacionDeEgreso_id) 
        references OperacionDeEgreso

    alter table OperacionDeEgreso_Usuario 
        add constraint FK_h66kc0b7t32eejydk2bwl1lu2 
        foreign key (usuariosRevisores_id) 
        references Usuario

    alter table OperacionDeEgreso_Usuario 
        add constraint FK_ertofip14bbb7trqicb9cbtnc 
        foreign key (OperacionDeEgreso_id) 
        references OperacionDeEgreso

    alter table OperacionDeEgreso_ValidacionPresupuestos 
        add constraint FK_c56yr5j34s9eh1kegbjolhiy0 
        foreign key (validacionesPresupuesto_id) 
        references ValidacionPresupuestos

    alter table OperacionDeEgreso_ValidacionPresupuestos 
        add constraint FK_p6u0jfxg4m4mkq81mtg5d8wvt 
        foreign key (OperacionDeEgreso_id) 
        references OperacionDeEgreso

    alter table Presupuesto 
        add constraint FK_95qaowgsm6agb4khctp0va2xf 
        foreign key (OperacionDeEgreso_id) 
        references OperacionDeEgreso

    alter table Proveedor 
        add constraint FK_hihr4t56yey6ytenl7rvao2hx 
        foreign key (direccionPostal_id) 
        references DireccionPostal

    alter table Reporte 
        add constraint FK_r27x7uwlkae82dlqqehnlf7xh 
        foreign key (etiqueta_identificador) 
        references Etiqueta

    alter table Reporte_OperacionDeEgreso 
        add constraint FK_e9qochl24fekyaq6i3eir94uh 
        foreign key (operaciones_id) 
        references OperacionDeEgreso

    alter table Reporte_OperacionDeEgreso 
        add constraint FK_s577lr9me83iidrxnj3t3iqc3 
        foreign key (Reporte_id) 
        references Reporte

    alter table Usuario 
        add constraint FK_ssxorje6rxndvfgggwlhnd46j 
        foreign key (tipo_id) 
        references TipoUsuario
